/**
 * generate-icons.js
 *
 * Reads SVG path data from @material-symbols/svg-400 (outlined and filled)
 * and generates a single Icon.tsx component with all paths inlined.
 * This avoids any external icon requests (TS §8 CSP, DD §11).
 *
 * Run: node scripts/generate-icons.js
 */
const fs = require('fs');
const path = require('path');

// Map from our icon name → file name in the package.
// expand_more does not exist in this version; keyboard_arrow_down is identical.
const iconsMap = {
  'shield_person': 'shield_person',
  'shield': 'shield',
  'verified': 'verified',
  'check_circle': 'check_circle',
  'warning': 'warning',
  'gpp_maybe': 'gpp_maybe',
  'lock': 'lock',
  'science': 'science',
  'error': 'error',
  'info': 'info',
  'expand_more': 'keyboard_arrow_down',
  'chevron_right': 'chevron_right',
  'arrow_back': 'arrow_back',
  'add_circle': 'add_circle',
  'security': 'security',
  'progress_activity': 'progress_activity',
  'search': 'search',
  'download': 'download',
  'print': 'print',
  'menu': 'menu',
  'close': 'close',
  'delete': 'delete',
  'more_vert': 'more_vert',
  'chat': 'chat',
  'mail': 'mail',
};

const svgDir = path.join(__dirname, '../node_modules/@material-symbols/svg-400/outlined');
const outPath = path.join(__dirname, '../apps/web/src/components/Icon.tsx');

/**
 * Extract the inner content and viewBox from an SVG file.
 */
function extractSvg(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const viewBoxMatch = content.match(/viewBox="([^"]+)"/);
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 -960 960 960';
  const innerMatch = content.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  const inner = innerMatch ? innerMatch[1].trim() : '';
  return { viewBox, inner };
}

// Verify all icons exist before generating
const missing = [];
for (const [name, file] of Object.entries(iconsMap)) {
  const outlined = path.join(svgDir, `${file}.svg`);
  const filled = path.join(svgDir, `${file}-fill.svg`);
  if (!fs.existsSync(outlined)) missing.push(`outlined/${file}.svg (for ${name})`);
  if (!fs.existsSync(filled)) missing.push(`outlined/${file}-fill.svg (for ${name})`);
}
if (missing.length > 0) {
  console.error('Missing SVG files:\n' + missing.join('\n'));
  process.exit(1);
}

// Get the viewBox from the first icon (they all use the same viewBox)
const sampleSvg = extractSvg(path.join(svgDir, 'shield.svg'));
const viewBox = sampleSvg.viewBox;

let out = `/**
 * Auto-generated by scripts/generate-icons.js — do not edit manually.
 * Source: @material-symbols/svg-400 (outlined and filled variants)
 * viewBox: ${viewBox}
 *
 * Requirements: TS §3 (Icons), TS §8 (CSP), DD §11, D-7
 */
import React from 'react';

export type IconName =
  | ${Object.keys(iconsMap).map(i => `'${i}'`).join('\n  | ')};

const ICON_VIEWBOX = '${viewBox}';

const outlinedPaths: Record<IconName, React.ReactNode> = {
`;

for (const [name, file] of Object.entries(iconsMap)) {
  const { inner } = extractSvg(path.join(svgDir, `${file}.svg`));
  out += `  '${name}': <>${inner}</>,\n`;
}
out += `};\n\n`;

out += `const filledPaths: Record<IconName, React.ReactNode> = {\n`;
for (const [name, file] of Object.entries(iconsMap)) {
  const { inner } = extractSvg(path.join(svgDir, `${file}-fill.svg`));
  out += `  '${name}': <>${inner}</>,\n`;
}
out += `};\n\n`;

out += `export interface IconProps extends React.SVGProps<SVGSVGElement> {
  /** The icon to render. */
  name: IconName;
  /** Use the filled variant (status/brand icons). Default: outlined (navigation). */
  filled?: boolean;
  /** Override the default 24px size. */
  size?: number;
}

/**
 * Renders a Material Symbols icon as an inline SVG.
 * Reserved 24px box with no layout shift (DD §11).
 * Fill=1 for status and brand icons, Fill=0 for navigation (DD §11).
 */
export function Icon({
  name,
  filled = false,
  size = 24,
  className,
  style,
  ...props
}: IconProps) {
  const paths = filled ? filledPaths : outlinedPaths;
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={ICON_VIEWBOX}
      fill="currentColor"
      width={size}
      height={size}
      className={\`rs-icon\${className ? \` \${className}\` : ''}\`}
      style={{ flexShrink: 0, ...style }}
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      {paths[name]}
    </svg>
  );
}
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out);
console.log(`Icon component generated at ${outPath}`);
console.log(`  ${Object.keys(iconsMap).length} icons, viewBox: ${viewBox}`);
